variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "env" {}
variable "subnets" {}
variable "vpc_id" {}
variable "sg_cidrs" {}
variable "kms" {}
variable "parameter_group_family" {}
variable "instance_count" {}
variable "project_name" {}
variable "tags" {}